DB_HOST = "localhost"
DB_PORT = 3306
DB_NAME = "barkeep"
DB_USER = "root"
DB_PASSWORD = "changeme"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
OAUTH2_CLIENT_ID = "your client id here"
OAUTH2_CLIENT_SECRET = "your client secret here"
BARKEEP_HOSTNAME = "barkeep.cfapps.io"
REPOS_ROOT = "barkeep_repos"
UNICORN_PID_FILE = "/tmp/barkeep-unicorn.pid"
UNICORN_SOCKET = "/tmp/barkeep-unicorn.sock"
UNICORN_WORKERS = 4
RESQUE_WORKERS = 4
RACK_ENV = "production"
GMAIL_ADDRESS = "uaabarkeep@gmail.com"
GMAIL_PASSWORD = "fluffy10kerberos"
COOKIE_SESSION_SECRET = "This shoasdasdasuld be a long, random, secret string."
REDIS_DB = 0
REDIS_DB_FOR_RESQUE = 1
